const placesData = {
    cafe1: "메트로폴리스",
    cafe2: "엔젤로",
    cafe3: "시프스",
    cafe4: "에이프릴사워",
    cafe5: "호이폴로이 커피로스터스",
    cafe6: "라라브레드 공릉점",
    cafe7: "트위그 페스츄리",
    cafe8: "리브인오후",
    cafe9: "던모스",
    cafe10: "올리볼렌",
    cafe11: "미라쥬양과점",
    cafe12: "파운드그레도",
    cafe13: "마카모예 브레드바",
    cafe14: "온고이",
    cafe15: "오피셜커피",
    cafe16: "카페쉔",
    cafe17: "우아즈",
    cafe18: "플랫커피",
    cafe19: "딜리스",
    cafe20: "샹드마르스커피 공릉점",
    cafe21: "원주율",
    cafe22: "무드쉐어",
    cafe23: "달콤한순간",
    cafe24: "따미커피",
    cafe25: "카페에이치",
    cafe26: "영스테이 공릉점",
    cafe27: "메모아",
    cafe28: "모퉁이",
    cafe29: "비스킷플로어",
    cafe30: "오누이",
    cafe31: "이너모스트",
    cafe32: "커피콩",
    restaurant1: "쪼매매운떡볶이",
    restaurant2: "바우네수제왕돈까스",
    restaurant3: "핏짜굽는언니 공릉점",
    restaurant4: "더맛나곱창",
    restaurant5: "마인하우스",
    restaurant6: "샹츠마라",
    restaurant7: "찬이네곱창",
    restaurant8: "세겹먹는날",
    restaurant9: "아리랑핫도그 과학기술대점",
    restaurant10: "소문날라",
    restaurant11: "기린",
    restaurant12: "이정림수제햄부대찌개",
    restaurant13: "로지스시",
    restaurant14: "네코정",
    restaurant15: "열화철판",
    restaurant16: "무봉리토종순대국 공릉점",
    restaurant17: "왕짜장",
    restaurant18: "스시쟁이",
    restaurant19: "원조강영숙봉평메밀촌 본점",
    restaurant20: "공릉순두부",
    restaurant21: "지호한방삼계탕 공릉점",
    restaurant22: "로지다이닝키친",
    restaurant23: "등촌샤브칼국수 공릉점",
    restaurant24: "알러이",
    restaurant25: "일상다반",
    restaurant26: "원조이모네연탄불곱창",
    restaurant27: "가원양꼬치",
    restaurant28: "신미방마라탕 공릉점",
    restaurant29: "시작이밤이다",
    restaurant30: "아소코",
    restaurant31: "인차이나",
    restaurant32: "비스트로 무크",
    restaurant33: "오대양횟집",
    restaurant34: "닭한마리 공릉본점",
    restaurant35: "공도",
    restaurant36: "에그머니",
    restaurant37: "코쿠카츠",
    restaurant38: "오늘의파스타",
    restaurant39: "하노이별 공릉점",
    restaurant40: "페페그라노",
    restaurant41: "웨일스",
    restaurant42: "차차",
    restaurant43: "주세프명인",
    restaurant44: "솔직하다",
    restaurant45: "퍼스트쿡카츠",
    restaurant46: "경성초밥",
    restaurant47: "스시락2호점",
    restaurant48: "디에트로",
    restaurant49: "태릉양꼬치양갈비",
    restaurant50: "제일콩집",
    restaurant51: "석천숯불갈비",
    restaurant52: "히딩크의 추억"
};

window.placesData = placesData;